<?php

/**
 * Fotos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author Michal Stanke <michal.stanke@mikk.cz>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Fotos extends BaseFotos {

    public function setGalleryID($id) {
        $this->gallery_id = $id;
    }

    public function setName($name) {
        $this->name = htmlspecialchars($name);
    }

    public function setFileName($filename) {
        $this->filename = htmlspecialchars($filename);
    }
    
    public function getFileName() {
        return $this->filename;
    }

    public function setThumbname($thumbname) {
        $this->thumbname = htmlspecialchars($thumbname);
    }

}
