<?php

/**
 * Galleries
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author Michal Stanke <michal.stanke@mikk.cz>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Galleries extends BaseGalleries {

    public function getID() {
        return $this->id;
    }

    public function getUserID() {
        return $this->user_id;
    }
    
    public function setOwner($id) {
        $this->user_id = $id;
    }

    public function getName() {
        return $this->name;
    }

    public function setName($name) {
        $this->name = htmlspecialchars($name);
    }

    public function getUploadedTime() {
        return $this->uploaded;
    }

    public function getDescription() {
        return $this->description;
    }

    public function setDescription($description) {
        $this->description = htmlspecialchars($description);
    }

}
