<?php

/**
 * RolesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @author Michal Stanke <michal.stanke@mikk.cz>
 */
class RolesTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object RolesTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Roles');
    }

    /**
     * Returns the Roles object corresponding to the given user.
     * 
     * @param Users $user
     * @return Roles users role
     */
    public function getForUser(Users $user) {
        $roleID = $user->getRoleID();
        $q = Doctrine_Query::create()
                ->from('roles r')
                ->where('r.id = ?', $roleID);
        return $q->fetchOne();
    }

    public function getAll() {
        $q = Doctrine_Query::create()
                ->select('r.id, r.name')
                ->from('roles r')
                ->orderBy('r.id ASC');
        return $q->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
    }

}
