<?php

/**
 * Roles
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author Michal Stanke <michal.stanke@mikk.cz>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Roles extends BaseRoles {

    public function isAdmin() {
        return $this->admin;
    }
    
    public function allGalleries() {
        return $this->allgalleries;
    }

}
