<?php

/**
 * Settings
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author Michal Stanke <michal.stanke@mikk.cz>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Settings extends BaseSettings
{
    public function setValue($value) {
        $this->value = $value;
    }
    
    public function setName($name) {
        $this->name = htmlspecialchars($name);
    }
}