<?php

/**
 * SettingsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @author Michal Stanke <michal.stanke@mikk.cz>
 */
class SettingsTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object SettingsTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Settings');
    }

    /**
     * Returns the setting value from the settings table.
     * 
     * @param string $name name of the setting
     * @return string value
     */
    public function getSettingValue($name) {
        return $this->getSetting($name)->value;
    }

    /**
     * Returns the Settings object from the settings table.
     * 
     * @param string $name name of the setting
     * @return Settings setting
     */
    public function getSetting($name) {
        $q = Doctrine_Query::create()
                ->from('settings s')
                ->where('s.name = ?', $name);
        return $q->fetchOne();
    }

}
